// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmjpiwejglgyznvwjozp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtanBpd2VqZ2xneXpudndqb3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NDY3NTUsImV4cCI6MjA3NDUyMjc1NX0.HBbDUxkNEvUz4S3s-h_PEyRww3qEFwguHA1a2hRJTHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});